#
# Copyright (c) 2019-2025 OPPEN321
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/zhiern/ZeroWrt
# Description: Build OpenWrt using GitHub Actions

name: 💻 自定义编译（请勿使用）

on:
  workflow_dispatch:
           
jobs:
  build:
    name: Build ${{ github.event.inputs.device }}
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        path: ZeroWrt

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        echo build_dir="/builder" >> "$GITHUB_ENV"
        echo build_version="v24" >> "$GITHUB_ENV"

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Compile OpenWrt
      id: compile
      run: |
        export BUILD_FAST=y ENABLE_BPF=y ENABLE_LTO=y ENABLE_OTA=y LAN=10.0.0.1 GCC_VERSION=GCC15 web_server=nginx mihomo_core=meta
        bash <(curl -sS http://127.0.0.1:8080/openwrt/build.sh) v24 rockchip
